from qumpy.simulators import AnalyticDoubleSymmetricPotentialTransmissionSimulator

# Simulate the transmission

transmission_sim = AnalyticDoubleSymmetricPotentialTransmissionSimulator(V0=1.0)
transmission_sim.show_transmission_plot()