from qumpy.simulators import AnalyticDoubleSymmetricPotentialTransmissionSimulator

# Simulate the transmission

transmission_sim = AnalyticDoubleSymmetricPotentialTransmissionSimulator()
transmission_sim.show_transmission_plot()